# Generated by Django 5.1.5 on 2025-03-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_lesson_course"),
        ("users", "0002_alter_customuser_email_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="separately_paid_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson",
                to="materials.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
    ]
