# Generated by Django 5.1.5 on 2025-03-12 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_lesson_course"),
        ("users", "0003_payments_separately_paid_lesson"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payments",
            old_name="separately_paid_lesson",
            new_name="payment_lesson",
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course",
                to="materials.course",
                verbose_name="Оплаченный курс",
            ),
        ),
    ]
