# Generated by Django 5.1.5 on 2025-02-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Превью",
                null=True,
                upload_to="materials/preview",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="link",
            field=models.URLField(verbose_name="ссылка"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Превью",
                null=True,
                upload_to="materials/preview",
                verbose_name="Превью",
            ),
        ),
    ]
