# Generated by Django 5.1.5 on 2025-02-10 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_course_preview_alter_lesson_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание урока",
                null=True,
                verbose_name="Описание урока",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="ссылка"),
        ),
    ]
